development: &base
  adapter: mysql
  host: localhost
  database: freecycle_development
  username: root
  password: ""
  encoding: utf8
test:
  <<: *base
  database: freecycle_test
production:
  <<: *base
  database: freecycle-production
